version: "3"
services:
  mariadb:
    build:
      context: ./
      dockerfile: ./docker/mariadb/dockerfile
    expose:
      - "3306"
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=ssbd03
      - MYSQL_ROOT_PASSWORD=ssbd03tua
    volumes:
      - dbvolume:/var/lib/mysql
  wildfly:
    build:
      context: ./
      dockerfile: ./docker/wildfly/dockerfile
    expose:
      - "8443"
    container_name: wildfly
    environment:
        - VIRTUAL_HOST=tua2020-02.tk
        - VIRTUAL_PORT=8443
        - VIRTUAL_PROTO=https
  nginx-proxy:
    build:
      context: ./
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - src/utils/certs:/etc/nginx/certs

volumes:
  dbvolume:
