 FROM jboss/wildfly
 RUN /opt/jboss/wildfly/bin/add-user.sh admin ssbd03tua --silent
 CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
 ADD ./target/ssbd03.war /opt/jboss/wildfly/standalone/deployments/
 ADD ./docker/mariadb-java-client-2.6.2.jar /opt/jboss/wildfly/standalone/deployments/