export const CHANGE_TITLE = "CHANGE_TITLE";
export const SET_AUTH = "SET_AUTH";
export const SWITCH_ROLE = "SWITCH_ROLE";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const SET_FORCE_PASSWORD_CHANGE = "SET_FORCE_PASSWORD_CHANGE";

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";

export const FETCH_MY_ACCOUNT_DETAILS = "FETCH_MY_ACCOUNT_DETAILS";
export const FETCH_ACCOUNT_DETAILS = "FETCH_ACCOUNT_DETAILS";
export const SET_ACCOUNT_DETAILS = "SET_ACCOUNT_DETAILS";

export const FETCH_ACCOUNT_LIST = "FETCH_ACCOUNT_LIST";
export const SET_ACCOUNT_LIST = "SET_ACCOUNT_LIST";

export const FETCH_ACCOUNT_REPORTS_LIST= "FETCH_ACCOUNT_REPORTS";
export const SET_ACCOUNT_REPORTS_LIST= "SET_ACCOUNT_REPORTS";

export const UPDATE_MY_ACCOUNT = "UPDATE_MY_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";

export const BUILD_BREADCRUMB = "BUILD_BREADCRUMB";
export const RESET_BREADCRUMB = "RESET_BREADCRUMB";

export const SET_ACTIVE = "SET_ACTIVE";
export const RESET_ACCOUNT_LIST_ERROR = "RESET_ACCOUNT_LIST_ERROR";

export const FETCH_ALL_OFFERS_LIST = "FETCH_ALL_OFFERS_LIST";
export const SET_ALL_OFFERS_LIST = "SET_ALL_OFFERS_LIST";
export const RESET_ALL_OFFERS_LIST_ERROR = "RESET_ALL_OFFERS_LIST_ERROR";
export const SET_OPEN = "SET_OPEN";
export const SET_VISIBLE = "SET_VISIBLE";
export const SET_CLOSED = "SET_CLOSED";
export const REMOVE_OFFER = "REMOVE_OFFER";

export const FETCH_ACTIVE_OFFERS_LIST = "FETCH_ACTIVE_OFFERS_LIST";
export const SET_ACTIVE_OFFERS_LIST = "SET_ACTIVE_OFFERS_LIST";
export const RESET_ACTIVE_OFFERS_LIST_ERROR = "RESET_ACTIVE_OFFERS_LIST_ERROR";

export const FETCH_STARSHIP_LIST = "FETCH_STARSHIP_LIST";
export const SET_STARSHIP_LIST = "SET_STARSHIP_LIST";
export const RESET_STARSHIP_LIST_ERROR = "RESET_STARSHIP_LIST_ERROR";
export const SET_OPERATIONAL = "SET_OPERATIONAL";

export const FETCH_APPLICATION_LIST = "FETCH_APPLICATION_LIST";
export const SET_APPLICATION_LIST = "SET_APPLICATION_LIST";
export const RESET_APPLICATION_LIST_ERROR = "RESET_APPLICATION_LIST_ERROR";

export const FETCH_MY_APPLICATION_DETAILS = "FETCH_MY_APPLICATION_DETAILS";
export const FETCH_APPLICATION_DETAILS = "FETCH_APPLICATION_DETAILS";
export const SET_APPLICATION_DETAILS = "SET_APPLICATION_DETAILS";

export const FETCH_MY_REVIEW_DETAILS = "FETCH_MY_REVIEW_DETAILS";
export const FETCH_REVIEW_DETAILS = "FETCH_REVIEW_DETAILS";
export const SET_REVIEW_DETAILS = "SET_REVIEW_DETAILS";

export const FETCH_OWN_APPLICATION_LIST = "FETCH_APPLICATION_LIST";
export const SET_OWN_APPLICATION_LIST = "SET_APPLICATION_LIST";
export const RESET_OWN_APPLICATION_LIST_ERROR = "RESET_APPLICATION_LIST_ERROR";

export const FETCH_OFFER_GUEST_DETAILS = "FETCH_OFFER_GUEST_DETAILS";
export const FETCH_OFFER_EMPLOYEE_DETAILS = "FETCH_OFFER_EMPLOYEE_DETAILS";
export const SET_OFFER_DETAILS = "SET_OFFER_DETAILS";
export const RESET_OFFER_DETAILS_ERROR = "RESET_OFFER_DETAILS_ERROR";

export const FETCH_STARSHIP_GUEST_DETAILS = "FETCH_STARSHIP_GUEST_DETAILS";
export const FETCH_STARSHIP_EMPLOYEE_DETAILS = "FETCH_STARSHIP_EMPLOYEE_DETAILS";
export const SET_STARSHIP_DETAILS = "SET_STARSHIP_DETAILS";
export const RESET_STARSHIP_DETAILS_ERROR = "RESET_STARSHIP_DETAILS_ERROR";

export const CANCEL_APPLICATION = "CANCEL_APPLICATION";

export const FETCH_GET_APPLICATION_DETAILS = 'FETCH_GET_APPLICATION_DETAILS';
export const SET_EDIT_APPLICATION_DETAILS = 'SET_EDIT_APPLICATION_DETAILS';
